site_name: Java on Mobile
site_url: https://openjdk-mobile.github.io
theme:
  name: material
  features:
    - navigation.expand
    - content.code.copy
    - search.highlight
    - search.share

extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - Mission: mission.md
  - OpenJDK/mobile: openjdk-mobile.md
  - Architecture: architecture.md
  - Platforms: platforms.md
  - iOS:
    - goals: ios.md
    - HelloWorld.jar: ios/helloworld.md
    - JavaFX apps: ios/javafx.md
    - Java libraries: ios/library.md
  - Android: android.md
  - Issues: issues.md
  - Roadmap: roadmap.md
  - Contributing: contributing.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - def_list

plugins:
  - search

